<a href="https://colab.research.google.com/github/dcallirgos/UTE_Fundamentos_de_Programacion/blob/main/Modulo3_Sesi%C3%B3n2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Números Aleatorios Discretos Uniformes**

Documentación Numpy: https://numpy.org/doc/stable/reference/random/

In [5]:
import numpy as np

Comandos:

**np.random.randint(low, high)**: Genera números enteros entre los valores low y high

**np.random.random_integers(low, high)**: Genera números enteros entre los valores low y high-1



In [12]:
# Generar un número aleatorio entre 23 y 42
# Es necesario sumar uno al valor high
valor_generado = np.random.randint(23, 42+1)
print(valor_generado)

28


In [35]:
# Lanzar dados
dado = np.random.randint(1, 6+1)
print(dado)

4


In [36]:
# Lanzar dados 20 veces
dado = np.random.randint(1, 6+1, 20)
print(dado)

[2 5 6 1 1 3 4 5 1 3 4 2 4 3 2 4 5 3 1 3]


In [17]:
# Calcular el valor promedio que obtengo en lanzar un dado
# Intuición: lanzo muchas veces el dado y apunto sus resultados, luego calculo el promedio

promedio_dado = np.random.randint(1, 6+1, 20)
print(promedio_dado)
print("El valor promedio calculado con 20 tiros:", np.mean(promedio_dado))

promedio_dado = np.random.randint(1, 6+1, 2_000)
print("El valor promedio calculado con 2,000 tiros:", np.mean(promedio_dado))

promedio_dado = np.random.randint(1, 6+1, 200_000)
print("El valor promedio calculado con 200,000 tiros:", np.mean(promedio_dado))

promedio_dado = np.random.randint(1, 6+1, 2_000_000)
print("El valor promedio calculado con 2,000,000 tiros:", np.mean(promedio_dado))

promedio_dado = np.random.randint(1, 6+1, 20_000_000)
print("El valor promedio calculado con 20,000,000 tiros:", np.mean(promedio_dado))

[1 4 3 5 1 2 6 2 3 6 3 4 1 2 4 2 1 4 3 2]
El valor promedio calculado con 20 tiros: 2.95
El valor promedio calculado con 2,000 tiros: 3.5095
El valor promedio calculado con 200,000 tiros: 3.501195
El valor promedio calculado con 2,000,000 tiros: 3.499548
El valor promedio calculado con 20,000,000 tiros: 3.50018935


1. Considere lanzar un dado 100 veces

a. ¿Cuántas veces se obtendrá el valor de 2?

b. ¿Cuántas veces se obtendrá el valor de 5?

c. ¿Cuántas veces se obtendrá el valor de 3 o 6?

In [25]:
# Esta fue mi solución pero no es la más eficiente en consumo de recursos máquina

dado2 = []
for i in range(1,101):
  a = np.random.randint(1, 6+1)
  dado2.append(a)
b = dado2.count(2)
print(b)

22


In [43]:
# Semilla: fijar los números aleatorios para que siempre salgan los mismos
np.random.seed(1)

# Generar los 100 lanzamientos
lanzamientos = np.random.randint(1, 6+1, 100)
print(lanzamientos)

es_dos = lanzamientos == 2
print("La cantidad de veces que se obtuvo dos:",np.sum(es_dos))

es_cinco = lanzamientos == 5
print("La cantidad de veces que se obtuvo cinco:",np.sum(es_cinco))

es_tres_seis = (lanzamientos == 3) + (lanzamientos ==6)
print("La cantidad de veces que se obtuvo tres o seis:",np.sum(es_tres_seis))


[6 4 5 1 2 4 6 1 1 2 5 6 5 2 3 5 6 3 5 4 5 3 5 6 3 5 2 2 1 6 2 2 6 2 2 1 5
 2 1 1 6 4 3 2 1 4 6 2 2 4 5 1 2 4 5 3 5 1 6 4 2 3 1 5 2 3 3 2 1 2 4 6 5 4
 6 2 4 1 1 3 3 2 4 5 3 1 1 2 2 6 4 1 1 6 6 5 6 3 5 4]
La cantidad de veces que se obtuvo dos: 22
La cantidad de veces que se obtuvo cinco: 17
La cantidad de veces que se obtuvo tres o seis: 29


In [44]:
import time

In [46]:
inicio = time.time()

dado2 = []
for i in range(1,1_000_000):
  a = np.random.randint(1, 6+1)
  dado2.append(a)
b = dado2.count(2)

fin = time.time()
print(b)
print("Tiempo de Ejecución:", fin-inicio)

166314
Tiempo de Ejecución: 3.6471192836761475


Considere lanzar dos dados 20 veces

a. ¿Cuántas veces se obtendrá el valor de 12?

b. ¿Cuántas veces se obtendrá el valor de 7?

c. ¿Cuántas veces se obtendrá un número impar como resultado?

In [53]:
# Generar los 20 lanzamientos en cada dado
lanzamientos1 = np.random.randint(1, 6+1, 20)
lanzamientos2 = np.random.randint(1, 6+1, 20)
print(lanzamientos1)
print(lanzamientos2)

es_doce = (lanzamientos1 + lanzamientos2) == 12
print("La cantidad de veces que se obtuvo doce:",np.sum(es_doce))

[5 3 2 2 4 1 5 3 6 6 3 1 3 5 1 1 6 6 6 3]
[2 1 2 6 5 5 1 1 6 3 3 4 2 1 4 3 1 2 3 2]
La cantidad de veces que se obtuvo doce: 1


In [ ]:
aleatorio1 = np.random.randint(1, 6+1, 20)
aleatorio2 = np.random.randint(1, 6+1, 20)
dosdados = aleatorio1+aleatorio2


**Variables Discretas Poisson**

Son ocurrencia en el tiempo

Ejemplos

* Personas que llegan a un banco en una hora
* Cantidad de Denuncias obtenidas en un día
* La Cantidad de aviones que aterrizan en el aeropuerto en una semana

Comandos:

**np.random.poisson(ocurrencias, cantidad de simulaciones)**

In [54]:
import numpy as np

In [60]:
# En un banco llegan en promedio 2000 personas por día
# Simule la cantidad de personas que llegarán en una semana
# Número de Ocurrencias = 2000
# Cantidad de Simulaciones = 7

valores_generados = np.random.poisson(2000,7)
print(valores_generados)

[2017 1972 2009 2030 1987 1979 2051]


Un banco recibe en promedio 20 clientes por hora, en un horario laboral cuantos
clientes recibirá en promedio.

In [75]:
# Una Simulación
valores_generados = np.random.poisson(20,8)
print(valores_generados)
print("Total de Clientes", np.sum(valores_generados))

[26 31 21 10 20 26 22 18]
Total de Clientes 174


In [80]:
# Una Simulación para 10 días
lista = []
contador = 1
for i in range(10):
  valores_generados = np.random.poisson(20,8)
  cantidad_semanal = np.sum(valores_generados)
  lista.append(cantidad_semanal)
  print("Semana", contador, "tuvo", cantidad_semanal, "clientes")
  contador = contador +1

lista = np.array(lista)
print("El promedio que se obtiene es", np.mean(lista))

Semana 1 tuvo 145 clientes
Semana 2 tuvo 146 clientes
Semana 3 tuvo 160 clientes
Semana 4 tuvo 173 clientes
Semana 5 tuvo 144 clientes
Semana 6 tuvo 150 clientes
Semana 7 tuvo 173 clientes
Semana 8 tuvo 131 clientes
Semana 9 tuvo 147 clientes
Semana 10 tuvo 135 clientes
El promedio que se obtiene es 150.4


**Tarea Ejercicio 5 y 6**

Correo: jyarascam@utec.edu.pe
