<a href="https://colab.research.google.com/github/dcallirgos/UTE_Fundamentos_de_Programacion/blob/main/Modulo3_Sesi%C3%B3n2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Números Aleatorios Discretos Uniformes**

Documentación Numpy: https://numpy.org/doc/stable/reference/random/

In [5]:
import numpy as np

Comandos:

**np.random.randint(low, high)**: Genera números enteros entre los valores low y high

**np.random.random_integers(low, high)**: Genera números enteros entre los valores low y high-1



In [12]:
# Generar un número aleatorio entre 23 y 42
# Es necesario sumar uno al valor high
valor_generado = np.random.randint(23, 42+1)
print(valor_generado)

28


In [35]:
# Lanzar dados
dado = np.random.randint(1, 6+1)
print(dado)

4


In [36]:
# Lanzar dados 20 veces
dado = np.random.randint(1, 6+1, 20)
print(dado)

[2 5 6 1 1 3 4 5 1 3 4 2 4 3 2 4 5 3 1 3]


In [17]:
# Calcular el valor promedio que obtengo en lanzar un dado
# Intuición: lanzo muchas veces el dado y apunto sus resultados, luego calculo el promedio

promedio_dado = np.random.randint(1, 6+1, 20)
print(promedio_dado)
print("El valor promedio calculado con 20 tiros:", np.mean(promedio_dado))

promedio_dado = np.random.randint(1, 6+1, 2_000)
print("El valor promedio calculado con 2,000 tiros:", np.mean(promedio_dado))

promedio_dado = np.random.randint(1, 6+1, 200_000)
print("El valor promedio calculado con 200,000 tiros:", np.mean(promedio_dado))

promedio_dado = np.random.randint(1, 6+1, 2_000_000)
print("El valor promedio calculado con 2,000,000 tiros:", np.mean(promedio_dado))

promedio_dado = np.random.randint(1, 6+1, 20_000_000)
print("El valor promedio calculado con 20,000,000 tiros:", np.mean(promedio_dado))

[1 4 3 5 1 2 6 2 3 6 3 4 1 2 4 2 1 4 3 2]
El valor promedio calculado con 20 tiros: 2.95
El valor promedio calculado con 2,000 tiros: 3.5095
El valor promedio calculado con 200,000 tiros: 3.501195
El valor promedio calculado con 2,000,000 tiros: 3.499548
El valor promedio calculado con 20,000,000 tiros: 3.50018935


1. Considere lanzar un dado 100 veces

a. ¿Cuántas veces se obtendrá el valor de 2?

b. ¿Cuántas veces se obtendrá el valor de 5?

c. ¿Cuántas veces se obtendrá el valor de 3 o 6?

In [25]:
# Esta fue mi solución pero no es la más eficiente en consumo de recursos máquina

dado2 = []
for i in range(1,101):
  a = np.random.randint(1, 6+1)
  dado2.append(a)
b = dado2.count(2)
print(b)

22


In [43]:
# Semilla: fijar los números aleatorios para que siempre salgan los mismos
np.random.seed(1)

# Generar los 100 lanzamientos
lanzamientos = np.random.randint(1, 6+1, 100)
print(lanzamientos)

es_dos = lanzamientos == 2
print("La cantidad de veces que se obtuvo dos:",np.sum(es_dos))

es_cinco = lanzamientos == 5
print("La cantidad de veces que se obtuvo cinco:",np.sum(es_cinco))

es_tres_seis = (lanzamientos == 3) + (lanzamientos ==6)
print("La cantidad de veces que se obtuvo tres o seis:",np.sum(es_tres_seis))


[6 4 5 1 2 4 6 1 1 2 5 6 5 2 3 5 6 3 5 4 5 3 5 6 3 5 2 2 1 6 2 2 6 2 2 1 5
 2 1 1 6 4 3 2 1 4 6 2 2 4 5 1 2 4 5 3 5 1 6 4 2 3 1 5 2 3 3 2 1 2 4 6 5 4
 6 2 4 1 1 3 3 2 4 5 3 1 1 2 2 6 4 1 1 6 6 5 6 3 5 4]
La cantidad de veces que se obtuvo dos: 22
La cantidad de veces que se obtuvo cinco: 17
La cantidad de veces que se obtuvo tres o seis: 29


In [44]:
import time

In [46]:
inicio = time.time()

dado2 = []
for i in range(1,1_000_000):
  a = np.random.randint(1, 6+1)
  dado2.append(a)
b = dado2.count(2)

fin = time.time()
print(b)
print("Tiempo de Ejecución:", fin-inicio)

166314
Tiempo de Ejecución: 3.6471192836761475


Considere lanzar dos dados 20 veces

a. ¿Cuántas veces se obtendrá el valor de 12?

b. ¿Cuántas veces se obtendrá el valor de 7?

c. ¿Cuántas veces se obtendrá un número impar como resultado?

In [53]:
# Generar los 20 lanzamientos en cada dado
lanzamientos1 = np.random.randint(1, 6+1, 20)
lanzamientos2 = np.random.randint(1, 6+1, 20)
print(lanzamientos1)
print(lanzamientos2)

es_doce = (lanzamientos1 + lanzamientos2) == 12
print("La cantidad de veces que se obtuvo doce:",np.sum(es_doce))

[5 3 2 2 4 1 5 3 6 6 3 1 3 5 1 1 6 6 6 3]
[2 1 2 6 5 5 1 1 6 3 3 4 2 1 4 3 1 2 3 2]
La cantidad de veces que se obtuvo doce: 1


In [ ]:
aleatorio1 = np.random.randint(1, 6+1, 20)
aleatorio2 = np.random.randint(1, 6+1, 20)
dosdados = aleatorio1+aleatorio2


**Variables Discretas Poisson**

Son ocurrencia en el tiempo

Ejemplos

* Personas que llegan a un banco en una hora
* Cantidad de Denuncias obtenidas en un día
* La Cantidad de aviones que aterrizan en el aeropuerto en una semana

Comandos:

**np.random.poisson(ocurrencias, cantidad de simulaciones)**

In [54]:
import numpy as np

In [60]:
# En un banco llegan en promedio 2000 personas por día
# Simule la cantidad de personas que llegarán en una semana
# Número de Ocurrencias = 2000
# Cantidad de Simulaciones = 7

valores_generados = np.random.poisson(2000,7)
print(valores_generados)

[2017 1972 2009 2030 1987 1979 2051]


Un banco recibe en promedio 20 clientes por hora, en un horario laboral cuantos
clientes recibirá en promedio.

In [75]:
# Una Simulación
valores_generados = np.random.poisson(20,8)
print(valores_generados)
print("Total de Clientes", np.sum(valores_generados))

[26 31 21 10 20 26 22 18]
Total de Clientes 174


In [80]:
# Una Simulación para 10 días
lista = []
contador = 1
for i in range(10):
  valores_generados = np.random.poisson(20,8)
  cantidad_semanal = np.sum(valores_generados)
  lista.append(cantidad_semanal)
  print("Semana", contador, "tuvo", cantidad_semanal, "clientes")
  contador = contador +1

lista = np.array(lista)
print("El promedio que se obtiene es", np.mean(lista))

Semana 1 tuvo 145 clientes
Semana 2 tuvo 146 clientes
Semana 3 tuvo 160 clientes
Semana 4 tuvo 173 clientes
Semana 5 tuvo 144 clientes
Semana 6 tuvo 150 clientes
Semana 7 tuvo 173 clientes
Semana 8 tuvo 131 clientes
Semana 9 tuvo 147 clientes
Semana 10 tuvo 135 clientes
El promedio que se obtiene es 150.4


**Tarea Ejercicio 5 y 6**

Correo: jyarascam@utec.edu.pe


**El número de personas que llegan a un hospital para ser atendidas es de 8 por hora.**

a. ¿Cuántas personas llegaran a lo largo de tres horas?

b. ¿En cuánto tiempo habrán llegado 15 personas?

c. ¿Si el máximo de personas que puede atender en un día el hospital es de 100,
cuantas horas habrán pasado hasta llegar a su límite?


In [1]:
import numpy as np

In [ ]:
# Los números aleatorios Poisson simulan cantidad de ocurrencias
# en periodos de tiempo (8 personas en promedio por hora)

# Parte a "np.random.poisson(ocurrencias, periodos)"

# Simular 10 escenarios
for i in range(1,11):
  x = np.random.poisson(8, 3)
  total = np.sum(x)
  print("Escenario", i, "Total de personas:", total)


In [21]:
# Parte b. En cuanto tiempo llegan 15 personas

suma = 0
tiempo_horas = 0
while suma <= 15:
  suma+= np.random.poisson(8)
  tiempo_horas+= 1

print("El tiempo en horas es de:", tiempo_horas)

El tiempo en horas es de: 2


In [28]:
# Parte b. En cuanto tiempo llegan 15 personas
# Con for y generando 1 millon de escenarios

lista = []
for i in range(1_000_000):
  suma = 0
  tiempo_horas = 0
  while suma <= 15:
    suma+= np.random.poisson(8)
    tiempo_horas+= 1
  lista.append(tiempo_horas)

lista = np.array(lista)
print("El promedio de tiempo para que lleguen 15 pacientes es:", np.mean(lista), "horas")


El promedio de tiempo para que lleguen 15 pacientes es: 2.493427 horas


In [38]:
# Parte c. ¿Si el máximo de personas que puede atender en un día el hospital
# es de 100, cuantas horas habrán pasado hasta llegar a su límite?

for i in range(1,11):
  suma = 0
  tiempo = 0
  while suma <= 100:
    suma+= np.random.poisson(8)
    tiempo+= 1
  print("Escenario", i, "tiempo en llegar a 100 personas es:", tiempo)

Escenario 1 tiempo en llegar a 100 personas es: 13
Escenario 2 tiempo en llegar a 100 personas es: 13
Escenario 3 tiempo en llegar a 100 personas es: 14
Escenario 4 tiempo en llegar a 100 personas es: 11
Escenario 5 tiempo en llegar a 100 personas es: 12
Escenario 6 tiempo en llegar a 100 personas es: 12
Escenario 7 tiempo en llegar a 100 personas es: 13
Escenario 8 tiempo en llegar a 100 personas es: 13
Escenario 9 tiempo en llegar a 100 personas es: 13
Escenario 10 tiempo en llegar a 100 personas es: 16


In [39]:
lista = []
for i in range(1_000_000):
  suma = 0
  tiempo = 0
  while suma <= 100:
    suma+= np.random.poisson(8)
    tiempo+= 1
  lista.append(tiempo)

lista = np.array(lista)
print("El promedio de tiempo para que lleguen 100 pacientes es:", np.mean(lista), "horas")

El promedio de tiempo para que lleguen 100 pacientes es: 13.125543 horas


**Variables Continuas Uniformes**

Toman valores en un intervalo (enteros y decimales). Todos los valores tienen la misma probabilidad de ocurrir

Ejemplos:

* El tiempo de espera de un bus.
* La temperatura del día.
* Velocidad del tiempo en Lima.

Comandos:

* **np.random.uniform(los, high)**

In [44]:
# Valor entre 5 y 10
valor_generado = np.random.uniform(5, 10)
valor_generado

7.407489360059785

In [51]:
# Valor entre -5 y 5
valor_generado = np.random.uniform(-5, 5)
valor_generado

-1.783953187398284

Si el tiempo de espera en minutos de un autobús sigue una variable uniforme de
extremos 0 y 10.

¿Cuánto es el tiempo promedio de espera?


In [53]:
lista = []
for i in range(1_000_000):
  tiempo_espera = np.random.uniform(0,10)
  lista.append(tiempo_espera)

lista = np.array(lista)
print("El tiempo promedio de espera del bus es de:", np.mean(lista), "minutos")

El tiempo promedio de espera del bus es de: 5.002193058815519 minutos


En la RENIEC el tiempo de atención promedio en una ventanilla es de 10 minutos.

a. Establezca una distribución uniforme para el tiempo de espera.

b. Si el banco dispone de 10 ventillas de atención, puede atender a 700
personas en un día.

c. Si se plantea optimizar al personal con el objetivo de disminuir el tiempo de
atención, cuanto debería ser el nuevo tiempo de atención con el objetivo de
atender a 700 personas por día.

d. Si se plantea expandir el número de ventanillas, cuantas son necesarias para
atender a 700 personas por día.  


In [60]:
# Parte a. Asumimos que la variable es uniforme de low = 5 y high= 15 minutos

# Parte b. Una ventanilla debería atender a 70 personas en 8 horas (480 minutos) --> IMPOSIBLE

# Simulación

tiempo_de_atenciones = np.random.uniform(5, 15, 70)
total_tiempo_atendido = np.sum(tiempo_de_atenciones)
print(total_tiempo_atendido)

683.5310897382918


In [62]:
for i in range(1,11):
  tiempo_de_atenciones = np.random.uniform(5, 15, 70)
  total_tiempo_atendido = np.sum(tiempo_de_atenciones)
  print("Escenario", i, "tiempo en atender a las 70 personas es:", total_tiempo_atendido, "minutos")

Escenario 1 tiempo en atender a las 70 personas es: 696.2238947216517 minutos
Escenario 2 tiempo en atender a las 70 personas es: 653.7391909234661 minutos
Escenario 3 tiempo en atender a las 70 personas es: 720.3512797077626 minutos
Escenario 4 tiempo en atender a las 70 personas es: 706.4847579568755 minutos
Escenario 5 tiempo en atender a las 70 personas es: 712.1627110867895 minutos
Escenario 6 tiempo en atender a las 70 personas es: 707.5088014581539 minutos
Escenario 7 tiempo en atender a las 70 personas es: 689.8561385333832 minutos
Escenario 8 tiempo en atender a las 70 personas es: 699.869834215818 minutos
Escenario 9 tiempo en atender a las 70 personas es: 725.4464456635155 minutos
Escenario 10 tiempo en atender a las 70 personas es: 713.2084629374202 minutos


In [65]:
# Parte c. Tiempos de atención para poder atender 700 personas

minimo = 5
maximo = 8

for i in range(1,11):
  tiempo_de_atenciones = np.random.uniform(minimo, maximo, 70)
  total_tiempo_atendido = np.sum(tiempo_de_atenciones)
  print("Escenario", i, "tiempo en atender a las 70 personas es:", total_tiempo_atendido, "minutos")

Escenario 1 tiempo en atender a las 70 personas es: 451.42314924018586 minutos
Escenario 2 tiempo en atender a las 70 personas es: 460.3888936053372 minutos
Escenario 3 tiempo en atender a las 70 personas es: 459.85204672425664 minutos
Escenario 4 tiempo en atender a las 70 personas es: 451.97493773639434 minutos
Escenario 5 tiempo en atender a las 70 personas es: 448.98778592903653 minutos
Escenario 6 tiempo en atender a las 70 personas es: 440.24836393168 minutos
Escenario 7 tiempo en atender a las 70 personas es: 462.29751582726595 minutos
Escenario 8 tiempo en atender a las 70 personas es: 462.5937366573365 minutos
Escenario 9 tiempo en atender a las 70 personas es: 447.47732388472133 minutos
Escenario 10 tiempo en atender a las 70 personas es: 445.22887775749564 minutos


In [69]:
# Parte d. Cuántas ventanillas se requeririan
# 700 personas por atender N ventanillas, las personas por ventanilla es de 700/N en 8 horas (480 minutos)

Nclientes = 700
Nventanillas = 16
Natenciones_por_ventanilla = Nclientes//Nventanillas

for i in range(1,11):
  tiempo_de_atenciones = np.random.uniform(5, 15, Natenciones_por_ventanilla)
  total_tiempo_atendido = np.sum(tiempo_de_atenciones)
  print("Escenario", i, "tiempo en atender es:", total_tiempo_atendido, "minutos")


Escenario 1 tiempo en atender es: 433.38170034124323 minutos
Escenario 2 tiempo en atender es: 446.1347655926573 minutos
Escenario 3 tiempo en atender es: 394.1936523058915 minutos
Escenario 4 tiempo en atender es: 435.1045951919922 minutos
Escenario 5 tiempo en atender es: 463.8289619496186 minutos
Escenario 6 tiempo en atender es: 438.73417306797376 minutos
Escenario 7 tiempo en atender es: 388.7592489906331 minutos
Escenario 8 tiempo en atender es: 461.8533292372135 minutos
Escenario 9 tiempo en atender es: 413.29832313309595 minutos
Escenario 10 tiempo en atender es: 442.5937307449793 minutos


**Variables Continuas Normales**

Son variables que especifican su valor medio y su margen de error

Comando

** *np.random.normal(media, error, cantidad)**

In [79]:
# Un fabricante de piezas de metal producen unos aros de aluminio
# de 80 cm. con un error de 2 cm.
# Genere algunas medidas de sus piezas producidas

valor_generado = np.random.normal(80, 2)
print(valor_generado)

81.25173884982487


In [80]:
valor_generado = np.random.normal(80, 2, 10)
print(valor_generado)

[80.28946683 79.3971691  79.15940881 81.9450932  79.88886421 82.76764007
 79.75258541 79.71733187 81.38302353 82.85856054]


Cierta empresa productora de botellas de vino conoce que la distribución del grado de alcohol es una variable normal de media 11 y de varianza 2. Por normativas legales, las botellas de vino deben de tener una cantidad menor de 11.5 grados de alcohol para poder ser enviadas a las distribuidoras. ¿De un lote de 5000 botellas cuantas serán aceptadas?

varianza = error**2


In [90]:
for i in range(1,11):
  botellas = np.random.normal(11, 2**0.5, 5_000)
  aceptado = botellas < 11.5
  cantidad_aceptada = np.sum(aceptado)
  print("Escenario", i, "se aceptan:", cantidad_aceptada)

Escenario 1 se aceptan: 3145
Escenario 2 se aceptan: 3294
Escenario 3 se aceptan: 3203
Escenario 4 se aceptan: 3126
Escenario 5 se aceptan: 3180
Escenario 6 se aceptan: 3152
Escenario 7 se aceptan: 3168
Escenario 8 se aceptan: 3138
Escenario 9 se aceptan: 3216
Escenario 10 se aceptan: 3109
