<a href="https://colab.research.google.com/github/dcallirgos/UTE_Fundamentos_de_Programacion/blob/main/modulo_2/3.%20Numpy%20I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >

<h1 align=center><font size = 5> Numpy - Parte I
</font></h1>

---

## Tabla de Contenidos

<div class="alert alert-block alert-info" style="margin-top: 20px">

<font size = 3>
    
1. <a href="#item31">Trabajando con arrays </a>
2. <a href="#item31">Algebra Matricial con arrays</a>  

</font>
</div>

---

# 1. Trabajando con Arrays 

In [1]:
#importando numpy
import numpy as np

In [4]:
np.array(['jhon','marco','diego']) #Se identifica el array como texto, string, pero no va a aceptar todas las operaciones númericas para lo cual se usa el array. El Array no está pensado para texto

array(['jhon', 'marco', 'diego'], dtype='<U5')

In [5]:
np.array([20, 25, 33, 24, 28, 32],
         [8, 3, 10, 1, 5, 9])

TypeError: ignored

In [4]:
#Sale error anteriormente  porque cuando le agrego una segunda dimensión (dos filas y 6 columnnas) necesita de una estructura más grande; de ahi el doble parentesis
np.array(([20, 25, 33, 24, 28, 32],
          [ 8,  3, 10,  1,  5,  9],
          [ 5,  6,  5,  7,  5,  4]))



array([[20, 25, 33, 24, 28, 32],
       [ 8,  3, 10,  1,  5,  9],
       [ 5,  6,  5,  7,  5,  4]])

In [7]:
import numpy as np
np.array([[[20, 25, 33, 24, 28, 32],
           [ 8,  3, 10,  1,  5,  9],
           [ 5,  6,  5,  7,  5,  4]],
           [[20, 25, 33, 24, 28, 32],
           [ 8,  3, 10,  1,  5,  9],
           [ 5,  6,  5,  7,  5,  4]]])

array([[[20, 25, 33, 24, 28, 32],
        [ 8,  3, 10,  1,  5,  9],
        [ 5,  6,  5,  7,  5,  4]],

       [[20, 25, 33, 24, 28, 32],
        [ 8,  3, 10,  1,  5,  9],
        [ 5,  6,  5,  7,  5,  4]]])

In [15]:
a = np.array([[[1, 2, 3, 4,  5],
              [3, 4, 6, 8, 10],
              [6, 7, 8, 10, 2]],
             [[1, 2, 3, 4,  5],
              [3, 4, 6, 8, 10],
              [6, 7, 8, 10, 2]]])
print(a)

[[[ 1  2  3  4  5]
  [ 3  4  6  8 10]
  [ 6  7  8 10  2]]

 [[ 1  2  3  4  5]
  [ 3  4  6  8 10]
  [ 6  7  8 10  2]]]


In [ ]:
# Array de una dimensión
a1 = np.array([1, 2, 3])
print(a1)

In [ ]:
# Array de dos dimensiones
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)

In [ ]:
# Array de tres dimensiones
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)

### Otras formas de crear arrays

In [16]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [20]:
np.zeros((3,3)) #Crea un Array de 3x3. Si queremos un vectos sería np.zeros((3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.zeros((3, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [30]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [32]:
# Genera una matriz de a x b con el valor que se solicite. En el ejemplo, genera una matriz 3 x 3 con el valor 69
np.full((3,3), 69)

array([[69, 69, 69],
       [69, 69, 69],
       [69, 69, 69]])

In [33]:
np.identity(6) #La matriz identidad contiene 1 en la diagonal y 0 a los lados. Recordar que la matriz siempre es cuadrada

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [35]:
np.arange(1, 15, 2) #Va del 1 al 15 de 2 en 2. Los parámetros yo los defino


array([ 1,  3,  5,  7,  9, 11, 13])

In [39]:
np.arange(0, 30, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [49]:
# Me permite generar un Array de una cantidad de valores equidistantes entre dos valores; np.linspace(valor de inicio, valor final, cantidad de valores)
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [52]:
# Siempre devuelve valores contenidos entre 0 y 1
np.random.random((3, 3)) 

array([[0.73783805, 0.17228074, 0.97233735],
       [0.34443485, 0.48912126, 0.88980701],
       [0.33236593, 0.1965172 , 0.23260495]])

In [60]:
# random.randit me permite generar números aleatorios entre 0 y el valor que le coloque como parámetro
np.random.randint(99)

77

In [61]:
# Utiliznado un List Compresion puede generar una lista con número aleatorios
[np.random.randint(99) for i in range(0,5)]

[13, 78, 89, 52, 74]

In [64]:
# Si lo quiero en un array
np.array([np.random.randint(99) for i in range(0,5)])

array([44, 33, 82, 54, 75])

### Atributos de un array

In [71]:
my_array = np.identity(5)
print(my_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [73]:
#Devuelve el número de dimensiones del array
my_array.ndim

2

In [75]:
#Devuelve una tupla con las dimensiones del array
my_array.shape

(5, 5)

In [77]:
#Devuelve el número de elementos del array
my_array.size

25

In [78]:
#Devuelve el tipo de datos de los elementos del array
my_array.dtype

dtype('float64')

### Acceder a elementos del array

In [79]:

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[1, 0]) # Esto le dice del array "a" anda al primer elemento y dentro del primer elemento saca la posición 0. La matriz [1 , 2, 3] es el valor 0 por tanto el valor 1 es la matriz [4 ,5 ,6] 

4


In [81]:
# Cúal será la forma de extraer el elemento 3 del array
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[0, 2])

3


In [82]:
# Cúal será la forma de extraer el elemento 6 del array
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[1, 2])

6


In [92]:
a = np.array([[[1, 2, 3], [4, 5, 6], [4, 5, 6], [11, 12, 13]],
              [[1, 2, 3], [4, 5, 99], [4, 5, 6], [11, 12, 13]]])

print(a[1, 1, 2])

99


In [93]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 4,  5,  6],
        [11, 12, 13]],

       [[ 1,  2,  3],
        [ 4,  5, 99],
        [ 4,  5,  6],
        [11, 12, 13]]])

In [95]:
a.ndim

3

In [96]:
a.shape

(2, 4, 3)

In [97]:
a.size

24

In [ ]:
print(a[1][0])

In [ ]:
print(a[:, 0:2])

In [103]:
a = np.array([[1, 2, 3, 4, 5],
             [1, 2, 3, 7, 8]])

# Para extraer el elmento 4 y 5 del primera dimensión y el 7 y 8 de la segunda dimensión
a[:, 3:]

array([[4, 5],
       [7, 8]])

In [106]:
a = np.array([[1, 2, 3, 4, 5],
              [1, 2, 3, 7, 8],
              [10, 11, 30, 77, 18]])

a[1:, 2:4]

array([[ 3,  7],
       [30, 77]])

### Filtrado de elementos de un array

In [112]:
# Para quedamer solo con los elementos partes de ambos vectores
a = np.array([[1, 2, 3], [4, 5, 6]])

a%2 == 0

array([[False,  True, False],
       [ True, False,  True]])

In [114]:
# Pero siempre perderá su dimensionalidad y me traerá en un array de una unica dimensión
a = np.array([[1, 2, 3], [4, 5, 6]])

a[(a%2 == 0)]

array([2, 4, 6])

In [116]:
# Pero puedo regresarle sus dimensiones con un reshape
a = np.array([[1, 2, 3, 8], [4, 5, 6, 7]])

temp = a[(a%2 == 0)]

temp.reshape(2,2)

array([[2, 8],
       [4, 6]])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[(a % 2 == 0)])

In [ ]:
print(a[(a % 2 == 0) &  (a > 2)])

### Operaciones matemáticas con arrays

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1, 1], [2, 2, 2]])

In [ ]:
print(a + b )

In [ ]:
print(a / b)

In [ ]:
print(a ** 2)

# 2. Álgebra matricial con arrays

### Producto escalar de dos vectores

u.dot(v): Devuelve el producto escalar de los vectores u y v.



In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([1, 0, 1])
print(a @ b)

In [ ]:
print(a.dot(b))

In [ ]:
a*b

### Módulo de un vector

norm(v): Devuelve el módulo del vector v.

In [ ]:
a = np.array([3, 4])

In [ ]:
print(np.linalg.norm(a))

### Producto de dos matrices

a.dot(b) : Devuelve el producto matricial de las matrices a y b siempre y cuando sus dimensiones sean compatibles.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a @ b)

In [ ]:
print(a.dot(b))

### Matriz traspuesta

In [ ]:
np.array([[1, 2, 3], [4, 5, 6]])
print(a.T)

### Traza de una matriz

a.trace() : Devuelve la traza (suma de la diagonal principal) de la matriz cuadrada a.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.trace())

### Determinante de una matriz

det(a) : Devuelve el determinante de la matriz cuadrada a.

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.det(a))

### Matriz inversa

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(a))

### Autovalores de una matriz


eigvals(a) : Devuelve los autovalores de la matriz cuadrada a.



In [ ]:
a = np.array([[1, 1, 0], [1, 2, 1], [0, 1, 1]])
print(np.linalg.eigvals(a))

### Autovectores de una matriz

eig(a) : Devuelve los autovalores y los autovectores asociados de la matriz cuadrada a.

In [ ]:
a = np.array([[1, 1, 0], [1, 2, 1], [0, 1, 1]])
print(np.linalg.eig(a))

solve(a, b) : Devuelve la solución del sistema de ecuaciones lineales con los coeficientes de la matriz a y los términos independientes de la matriz b.

In [ ]:
# Sistema de dos ecuaciones y dos incógnitas
# x + 2y = 1
# 3x + 5y = 2 
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
print(np.linalg.solve(a, b))


### Solución de un sistema de ecuaciones

---

# Gracias por completar este laboratorio!

---
