<a href="https://colab.research.google.com/github/dcallirgos/UTE_Fundamentos_de_Programacion/blob/main/modulo_2/3.%20Numpy%20I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >

<h1 align=center><font size = 5> Numpy - Parte I
</font></h1>

---

## Tabla de Contenidos

<div class="alert alert-block alert-info" style="margin-top: 20px">

<font size = 3>
    
1. <a href="#item31">Trabajando con arrays </a>
2. <a href="#item31">Algebra Matricial con arrays</a>  

</font>
</div>

---

# 1. Trabajando con Arrays 

In [ ]:
#importando numpy
import numpy as np

In [ ]:
# Array de una dimensión
a1 = np.array([1, 2, 3])
print(a1)

In [ ]:
# Array de dos dimensiones
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)

In [ ]:
# Array de tres dimensiones
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)

### Otras formas de crear arrays

In [ ]:
np.zeros((2, 2))

In [ ]:
np.ones((2, 2))

In [ ]:
np.full((2,2), 10)

array([[10, 10],
       [10, 10]])

In [ ]:
np.identity(3)

In [ ]:
np.arange(1, 9, 1)

In [ ]:
np.linspace(1, 9, 3)

In [ ]:
np.random.random((2, 2)) 

### Atributos de un array

In [ ]:
#Devuelve el número de dimensiones del array
a.ndim 

In [ ]:
#Devuelve una tupla con las dimensiones del array
a.shape

In [ ]:
#Devuelve el número de elementos del array
a.size

In [ ]:
#Devuelve el tipo de datos de los elementos del array
a.dtype

### Acceder a elementos del array

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[1, 0])

In [ ]:
print(a[1][0])

In [ ]:
print(a[:, 0:2])

### Filtrado de elementos de un array

In [9]:
import numpy as np

a = np.array([[1, 2, 3, 8], [4, 5, 6, 7]])
b = np.array([[3, 3, 4, 7], [1, 9, 6, 5]])
print(a[(a % 2 == 0)])
print(b[(b > 3)])

a.reshape(4,2)

[2 8 4 6]
[4 7 9 6 5]


array([[1, 2],
       [3, 8],
       [4, 5],
       [6, 7]])

In [ ]:
print(a[(a % 2 == 0) &  (a > 2)])

### Operaciones matemáticas con arrays

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1, 1], [2, 2, 2]])

In [13]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
b

array([[1, 1, 1],
       [2, 2, 2]])

In [15]:
print(a + b )

[[2 3 4]
 [6 7 8]]


In [16]:
print(a / b)

[[1.  2.  3. ]
 [2.  2.5 3. ]]


In [17]:
print(a ** 2)

[[ 1  4  9]
 [16 25 36]]


# 2. Álgebra matricial con arrays

### Producto escalar de dos vectores

u.dot(v): Devuelve el producto escalar de los vectores u y v.



In [41]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([1, 0, 1])


In [20]:
a

array([1, 2, 3])

In [21]:
b

array([1, 0, 1])

In [22]:
# Es una operación vectorial de dos matrices 3x1 (a) y de 1x3 (b) = (1x1 + 2x0 + 3x1) = 4
print (a @ b)

4


In [42]:
print(a.dot(b)) #.dot es igual que el @

4


In [24]:
a*b

array([1, 0, 3])

Ejercicio

a = np.array([[3, 5, 0], [1, 3, 2]])
b = np.array([[3, 5], [92, 16], [0, 77]])

Multiple algebraicamente a y b, para esto adapte la matriz b para que se pueda cumplir la multiplicación.

Multiplique de la misma forma pero ahora use un operador aritmético

In [43]:
# Multiple algebraicamente a y b, para esto adapte la matriz b para que se pueda cumplir la multiplicación.

import numpy as np

a = np.array([[3, 5, 0], [1, 3, 2]])
b = np.array([[55, 42], [92, 16], [0, 77]])

c = b.reshape(3, 2)

print(a@c)

[[625 206]
 [331 244]]


In [44]:
# Multiplique de la misma forma pero ahora use un operador aritmético

import numpy as np

a = np.array([[3, 5, 0], [1, 3, 2]])
b = np.array([[55, 42], [92, 16], [0, 77]])

c = b.reshape(2, 3)

print(a*c)

[[165 210   0]
 [ 16   0 154]]


### Módulo de un vector

El módulo (d) de un vector es el tamaño del vector

d = Raiz Cuadrada de la dimension1 al cuadrado +  dimension 2 al cuadrado +... dimensionN al cuadrado


norm(v): Devuelve el módulo del vector v.

In [45]:
a = np.array([3, 4])

In [46]:
print(np.linalg.norm(a))

5.0


In [47]:
a = np.array([3, 4, 5])
print(np.linalg.norm(a))

7.0710678118654755


### Producto de dos matrices

a.dot(b) : Devuelve el producto matricial de las matrices a y b siempre y cuando sus dimensiones sean compatibles.

In [48]:
# Ambas matrices son compatibles. a es 2x3 y la b es de 3x2
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a @ b)

[[14 14]
 [32 32]]


In [ ]:
print(a.dot(b))

### Matriz traspuesta

In [53]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [54]:
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


### Traza de una matriz

a.trace() : Devuelve la traza (suma de la diagonal principal) de la matriz cuadrada a.
Solo las matrices cuadradas tienen traza

In [57]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(a.trace())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [61]:
# Cuando las matrices no son cuadradas, Trace autocompleta con 0 para volverlas cuadradas
a = np.array([[9, 2, 3], [4, 5, 6]])
print(a)
print(a.trace())

[[9 2 3]
 [4 5 6]]
14


### Determinante de una matriz

det(a) : Devuelve el determinante de la matriz cuadrada a.

In [62]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.det(a))

-2.0000000000000004


### Matriz inversa

In [63]:
a = np.array([[1, 2],
              [3, 4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


### Autovalores de una matriz


eigvals(a) : Devuelve los autovalores de la matriz cuadrada a.



In [65]:
# Se puede utilizar para Analisis de Componentes Principales

a = np.array([[1, 1, 0], [1, 2, 1], [0, 1, 1]])
print(np.linalg.eigvals(a))

[ 3.00000000e+00  1.00000000e+00 -3.36770206e-17]


### Autovectores de una matriz

eig(a) : Devuelve los autovalores y los autovectores asociados de la matriz cuadrada a.

In [66]:
a = np.array([[1, 1, 0], [1, 2, 1], [0, 1, 1]])
print(np.linalg.eig(a))

(array([ 3.00000000e+00,  1.00000000e+00, -3.36770206e-17]), array([[-4.08248290e-01,  7.07106781e-01,  5.77350269e-01],
       [-8.16496581e-01,  2.61239546e-16, -5.77350269e-01],
       [-4.08248290e-01, -7.07106781e-01,  5.77350269e-01]]))


solve(a, b) : Devuelve la solución del sistema de ecuaciones lineales con los coeficientes de la matriz a y los términos independientes de la matriz b.

In [67]:
# Sistema de dos ecuaciones y dos incógnitas
# 1x + 2y = 1
# 3x + 5y = 2 

a = np.array([[1, 2], [3, 5]]) # Es la parte de las Ecuadciones

b = np.array([1,
              2]) # Es la parte de la solución
print(np.linalg.solve(a, b)) 


[-1.  1.]


In [69]:
# Sistema de dos ecuaciones y dos incógnitas
# 10x + 2y -3z = 1
# 12x + 5y +17z = 2
# 2x + 50y +2z = 0

a = np.array([[10, 2, -3],
              [12, 5, 17],
              [2, 50, 2]])
b = np.array([1,
              2,
              0])

print(np.linalg.solve(a, b)) 

[ 0.11310345 -0.00610837  0.03960591]


### Solución de un sistema de ecuaciones

---

# Gracias por completar este laboratorio!

---
